name: Build OpenClaw Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  OPENCLAW_IMAGE: openclaw-docker-cli:latest
  SANDBOX_IMAGE: openclaw-sandbox:bookworm-slim
  SANDBOX_COMMON_IMAGE: openclaw-sandbox-common:bookworm-slim
  SANDBOX_BROWSER_IMAGE: openclaw-sandbox-browser:bookworm-slim

permissions:
  packages: write
  contents: read
jobs:
  build_arm64:
    env:
      variant: arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Git Clone Action
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: openclaw/openclaw
          path: openclaw

      - name: Login Harbor
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build openclaw
        run: |
          cd openclaw
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.OPENCLAW_IMAGE }}-${{ env.variant }}
          DOCKER_BUILDKIT=1 docker build \
          --build-arg "OPENCLAW_DOCKER_APT_PACKAGES=" \
          --build-arg "OPENCLAW_EXTENSIONS=" \
          --build-arg "OPENCLAW_INSTALL_DOCKER_CLI=1" \
          -t "$IMAGE_ID" \
          -f "Dockerfile" \
          .
          docker push $IMAGE_ID
  

      - name: Build sandbox
        run: |
          cd openclaw
          ./scripts/sandbox-setup.sh
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.SANDBOX_IMAGE }}-${{ env.variant }}
          docker tag ${{ env.SANDBOX_IMAGE }} $IMAGE_ID
          docker push $IMAGE_ID

      - name: Build sandbox-common
        run: |
          cd openclaw
          ./scripts/sandbox-common-setup.sh
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.SANDBOX_COMMON_IMAGE }}-${{ env.variant }}
          docker tag ${{ env.SANDBOX_COMMON_IMAGE }} $IMAGE_ID
          docker push $IMAGE_ID

      - name: Build sandbox-browser
        run: |
          cd openclaw
          ./scripts/sandbox-browser-setup.sh
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.SANDBOX_BROWSER_IMAGE }}-${{ env.variant }}
          docker tag ${{ env.SANDBOX_BROWSER_IMAGE }} $IMAGE_ID
          docker push $IMAGE_ID

  build_amd4:
    env:
      variant: amd64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Git Clone Action
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: openclaw/openclaw
          path: openclaw

      - name: Login Harbor
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build openclaw
        run: |
          cd openclaw
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.OPENCLAW_IMAGE }}-${{ env.variant }}
          DOCKER_BUILDKIT=1 docker build \
          --build-arg "OPENCLAW_DOCKER_APT_PACKAGES=" \
          --build-arg "OPENCLAW_EXTENSIONS=" \
          --build-arg "OPENCLAW_INSTALL_DOCKER_CLI=1" \
          -t "$IMAGE_ID" \
          -f "Dockerfile" \
          .
          docker push $IMAGE_ID

      - name: Build sandbox
        run: |
          cd openclaw
          ./scripts/sandbox-setup.sh
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.SANDBOX_IMAGE }}-${{ env.variant }}
          docker tag ${{ env.SANDBOX_IMAGE }} $IMAGE_ID
          docker push $IMAGE_ID

      - name: Build sandbox-common
        run: |
          cd openclaw
          ./scripts/sandbox-common-setup.sh
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.SANDBOX_COMMON_IMAGE }}-${{ env.variant }}
          docker tag ${{ env.SANDBOX_COMMON_IMAGE }} $IMAGE_ID
          docker push $IMAGE_ID

      - name: Build sandbox-browser
        run: |
          cd openclaw
          ./scripts/sandbox-browser-setup.sh
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.SANDBOX_BROWSER_IMAGE }}-${{ env.variant }}
          docker tag ${{ env.SANDBOX_BROWSER_IMAGE }} $IMAGE_ID
          docker push $IMAGE_ID
